version: "2"

run:
  timeout: 5m
  tests: true

linters:
  exclusions:
    paths:
      - "frontend/node_modules/.*"
      - "node_modules/.*"
      - vendor
      - tmp
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec
  enable:
    # базовые проверки
    - govet
    - errcheck
    - staticcheck
    - ineffassign

    # стиль и читаемость
    # - revive
    - gocritic
    - misspell
    - whitespace
    - unconvert

    # безопасность
    - gosec

    # ошибки и nil
    - nilerr
    - nilnil
    - errorlint

    # производительность
    - prealloc
    - perfsprint

    # работа с контекстом (очень важно для backend)
    - noctx
    - contextcheck

    # HTTP и ресурсы
    - bodyclose

    # SQL / DB
    - sqlclosecheck

    # структурные проблемы
    - wastedassign

  settings:
    revive:
      severity: warning
      rules:
        - name: indent-error-flow
        - name: error-return
        - name: error-naming
        - name: var-naming
        - name: receiver-naming

    gocritic:
      enabled-tags:
        - performance
        - style
        - diagnostic

    gosec:
      excludes:
        - G404

formatters:
  enable:
    - gofmt
    - goimports

output:
  formats:
    - format: text
      path: stdout

  sort-order:
    - file
    - linter

  show-stats: true
