version: "3.8"

services:
  web:
    build: .
    command: uv run manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: uv run celery -A app worker --loglevel=info --concurrency=1
    volumes:
      - .:/app
    env_file: .env
    shm_size: "2gb"
    depends_on:
      - db
      - redis

  # Брокер задач
  redis:
    image: redis:alpine

  # База данных
  # db:
  #   image: postgres:13-alpine
  #   environment:
  #     - POSTGRES_DB=parser_db
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
