# Generated by Django 6.0 on 2025-12-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParsingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('PROCESSING', 'В работе'), ('DONE', 'Готово'), ('ERROR', 'Ошибка')], default='PENDING', max_length=20)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='results/')),
                ('error_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
