FROM oven/bun:alpine AS frontend
WORKDIR /build/front
COPY front/package.json .
RUN bun install
COPY front/ .
RUN bun run build -- --outDir /build/static/dist

FROM golang:alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
COPY --from=frontend /build/static/dist ./internal/static/dist
RUN CGO_ENABLED=0 GOOS=linux go build -o /api ./cmd/api

FROM alpine:latest
RUN apk --no-cache add ca-certificates
COPY --from=builder /api /api
EXPOSE 8080
CMD ["/api"]
 