FROM oven/bun:alpine AS build
WORKDIR /app
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile
COPY . .
RUN bun run build

FROM oven/bun:alpine
WORKDIR /app
COPY --from=build /app/dist ./dist
COPY --from=build /app/server.ts .
EXPOSE 3000
CMD ["bun", "run", "server.ts"]