FROM golang:alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /bot ./cmd/bot

FROM alpine:latest
RUN apk --no-cache add ca-certificates
COPY --from=builder /bot /bot
CMD ["/bot"]
 